services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - python-backend
      - flutter-backend
    command: sh -c "npm install && npm test -- --watchAll=false || true"

  backend:
    build: ./backend/flutter
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    command: sh -c "flutter pub get && flutter test || true"

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - ORACLE_PASSWORD=Oracle123
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD", "exit", "0"]

  ords:
    image: container-registry.oracle.com/database/ords:latest
    ports:
      - "8888:8888"
    depends_on:
      - oracle-db
