name: CI with Docker Compose

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  docker-compose-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and run containers
        working-directory: deployment
        run: docker compose up --build --abort-on-container-exit

      - name: Tear down
        working-directory: deployment
        run: docker compose down --volumes --remove-orphans
