name: CI with Docker Compose

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  docker-compose-ci:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Set up Docker Buildx (optional, helps with caching/multi-arch)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker (optional, if you push images later)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and run all containers via docker-compose
      - name: Build and run containers
        run: docker compose up --build --abort-on-container-exit

      # 5. Tear down containers after tests
      - name: Tear down
        run: docker compose down --volumes --remove-orphans
