jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache npm + pub
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
      - uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('backend/pubspec.lock') }}

      # Lint frontend
      - name: Run ESLint
        working-directory: frontend
        run: npm ci && npx eslint .

      # Build frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Test frontend
      - name: Test frontend
        working-directory: frontend
        run: npm test -- --watchAll=false

      # Test backend (unit)
      - name: Test backend
        working-directory: backend
        run: flutter pub get && flutter test

  integration-tests:
    runs-on: ubuntu-latest
    needs: lint-and-build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Oracle Container Registry
        run: echo "${{ secrets.OCR_PASSWORD }}" | docker login container-registry.oracle.com -u "${{ secrets.OCR_USERNAME }}" --password-stdin

      - name: Run docker-compose integration tests
        working-directory: deployment
        run: docker compose up --build --abort-on-container-exit

      - name: Tear down
        working-directory: deployment
        run: docker compose down --volumes --remove-orphans
